### ISSUE TITLE
Refactoring of the USB program

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab-usbprogram#1]
During a discussion we extracted following points:

Refactoring:
- [x] Reorganise structure to reduce code duplication
- [x] Use vendor & product ID instead of names
- [x] update installers
  - [x] Linux
  - [x] Windows
  - [x] Mac
- [x] Combine Arduino based robots into one connector
- [x] Tests

Additional features:
- [x] List with Robot selection (possibly multiple robots, disconnect and choose a different robot) #15
- [x] Return to default state after disconnect #15
- [x] Serial Monitor #16 

Most of these will become their own issues.

**Comment by boonto** [comment]
For the arduino based robots vendor & product id is used identify them.

**Comment by boonto** [comment]
The refactoring is mostly finished. The remaining ideas were transferred to the [wiki](https://github.com/OpenRoberta/robertalab/wiki/Open-Roberta-Robot-Connection-Program).
