### ISSUE TITLE
Unable to connect to NXT on Ubuntu 16.04

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/robertalab-usbprogram#11]
Hello,

I have compiled the usb-program with maven. Once started the program detects NXT ("Found NXT") but the button "verbinden" stays greyed. In effect I can not connect to the detected NXT. Java-Version should be o.k., half a year ago, I was able to connect to a EV3 (with ORUSB 2.3).

Perhaps you can help me to connect succesfully.

Cheers
corvus-albus

Starting on console I get the following messages (Note, that I turned off the NXT at 09:44:36): 

.../java -jar -Dfile.encoding=utf-8 ./OpenRobertaUSB-2.0.5-SNAPSHOT.jar 
30/08/2017 09:42:55.917 - [de.fhg.iais.roberta.usb.Main.configureLogger] - [INFO] - Logging to file: /home/ch/OpenRobertaUSB/OpenRobertaUSB.log
30/08/2017 09:42:56.100 - [de.fhg.iais.roberta.usb.Main$1.getLocals] - [CONFIG] - Language de
30/08/2017 09:42:56.109 - [de.fhg.iais.roberta.connection.EV3USBConnector.<init>] - [CONFIG] - Robot ip 10.0.1.1
Found NXT: Unknown 0016530A83FF
30/08/2017 09:43:18.219 - [de.fhg.iais.roberta.usb.Main.main] - [INFO] - NXT found!
30/08/2017 09:43:18.220 - [de.fhg.iais.roberta.ui.UIController.setConnector] - [CONFIG] - GUI setup done. Using NXTUSBBTConnector
30/08/2017 09:43:18.222 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Starting NXT Connector Thread.
30/08/2017 09:43:18.350 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Server address lab.open-roberta.org:80
Found NXT: Unknown 0016530A83FF
Got exception during close: java.io.IOException: Error in write
30.08.2017 09:44:36 de.fhg.iais.roberta.connection.NXTCommunicator playSound
INFO: playing disconnect sound sequence failed
30/08/2017 09:44:36.073 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [INFO] - RESET CONNECTION BECAUSE DISCONNECTED
30/08/2017 09:44:36.663 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [INFO] - No NXT device connected
30/08/2017 09:44:38.143 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [INFO] - No NXT device connected
30/08/2017 09:44:39.464 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [INFO] - No NXT device connected
Found NXT: GS01 0016530A83FF

**Comment by corvus-albus** [comment]
I forgot to write: java-version is "jre-8u144-linux-i586". 
I also tried java version "1.6.0_45", which worked connecting to EV3.

**Comment by bjost2s** [comment]
Nxt is only detected with java 32 bit. 1.6 should work, probably also 1.7. It is the Nxt driver that cannot work with 64 bit version. Therefor we put java 1.6, 32 bit into the installer.

**Comment by corvus-albus** [comment]
Thank you for your reply. In effect it is no problem with a java 64-bit enviroment. I know the error-message in 64-bit java. But my problem is different. The NXT is detected. 

Now I downloaded  jre-6u45-linux-i586.bin and tried again. I get the same situation as described above. The NXT is **detected**. Just the button in the GUI is still grey and I cannot click "verbinden". No click, no token, no established connection.

**Comment by bjost2s** [comment]
Sorry for missunderstanding, I meant detected by the USB Programm. When the USB Programm is started it immediately starts looking for connected robots at the usb ports. For NXT it already uses at this early stage a library which is supposed to work with the 32 bit Java runtime. So for me it looks like this part is not working in your setup. Once an NXT is detected by the program, the "verbinden" button becomes enabled.
Could you please check our installer instead. Please follow the instructions here: https://jira.iais.fraunhofer.de/wiki/display/ORInfo/Set+Up+NXT#SetUpNXT-Linux
and let us know, if you still cannot connect.

**Comment by corvus-albus** [comment]
I took your installer and installation was sucessfull as you can see from the output:
> Statusinformationen werden eingelesen.... Fertig
>»libusb-0.1-4:i386« ist bereits die neuste Version (2:0.1.12-28).
>»libxext6:i386« ist bereits die neuste Version (2:1.3.3-1).
>»libxi6:i386« ist bereits die neuste Version (2:1.7.6-1).
>»libxrender1:i386« ist bereits die neuste Version (1:0.9.9-0ubuntu1).
>»libxtst6:i386« ist bereits die neuste Version (2:1.2.2-1).
>»libc6-i386« ist bereits die neuste Version (2.23-0ubuntu9).
>0 aktualisiert, 0 neu installiert, 0 zu entfernen und 3 nicht aktualisiert.
>/etc/udev/rules.d/70-lego.rules found.
>groupadd: Gruppe »lego« existiert bereits.
>Benutzer ch wird zur Gruppe lego hinzugefügt.
>Der Benutzer »ch« ist bereits ein Mitglied der Gruppe »dialout«.
 
I checked that the udev rule is correct.

I started the usbprogram in a terminal:
>OpenRobertaUSB_2.0.4/java/bin/java -jar -Dfile.encoding=utf-8 OpenRobertaUSB_2.0.4/OpenRobertaUSB.jar
>03/09/2017 02:18:56.204 - [de.fhg.iais.roberta.usb.Main.configureLogger] - [INFO] - Logging to file: /home/ch/OpenRobertaUSB/OpenRobertaUSB.log
>03/09/2017 02:18:56.358 - [de.fhg.iais.roberta.usb.Main$1.getLocals] - [CONFIG] - Language de
>03/09/2017 02:18:56.362 - [de.fhg.iais.roberta.connection.EV3USBConnector.<init>] - [CONFIG] - Robot ip 10.0.1.1
>Found NXT: Unknown 0016530A83FF
>03/09/2017 02:19:18.047 - [de.fhg.iais.roberta.usb.Main.main] - [INFO] - NXT found!
>03/09/2017 02:19:18.049 - [de.fhg.iais.roberta.ui.UIController.setConnector] - [CONFIG] - GUI setup done. Using NXTUSBBTConnector
>03/09/2017 02:19:18.049 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Starting NXT Connector Thread.
>03/09/2017 02:19:18.056 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Server address lab.open-roberta.org:80
>Found NXT: Unknown 0016530A83FF

The output shows, that the NXT is found. But the button "verbinden" is still grey. It is the same result as with the compiled version.

Cheers corvus-albus

P.S. The NXT has lego-firmware  1.31, lsusb shows "Bus 006 Device 006: ID 0694:0002 Lego Group Mindstorms NXT"

**Comment by bjost2s** [comment]
Here is the output with java 32 1.6
![image](https://user-images.githubusercontent.com/1613069/30005879-5666de1c-90ec-11e7-99c1-b6d477f10d18.png)

**Comment by corvus-albus** [comment]
Thank you for your effort. I see it can work even in the same enviroment. It remains as a mystery why it does not work on my notebook. 
The output on the console is really the same - the result is different:
![bildschirmfoto vom 2017-09-04 08-19-21](https://user-images.githubusercontent.com/26668681/30014111-bccf89de-914a-11e7-887f-fd499737db3c.png)
If I get the clue, I will post it.

Many thanks
corvus-albus

**Comment by corvus-albus** [comment]
Just another attempt: 
As I switch off the NXT, for a second the GUI looks like everything is fine. 
![bildschirmfoto vom 2017-09-04 09-17-07](https://user-images.githubusercontent.com/26668681/30015747-69fb8908-9152-11e7-8285-c0ea37da3dae.png)
The error message says there is a write problem. Not really astonishing because the NXT is switched off. There is only slight hope but perhaps this gives a hint to solution. 
![output](https://user-images.githubusercontent.com/26668681/30016185-57c87b86-9154-11e7-883a-f39b5e7294fd.gif)
Cheers corvus-albus

**Comment by NestorLarroca** [comment]
Tengo el mismo problema. El programa encuentra el NXT pero no genera el Token.
El mensaje es: Found NXT: Unknown 001653105D1C

S.O. Ubuntu 16.04 de 32 bits
Version java: openjdk version "1.8.0_171"

Agradezco ayuda

**Comment by NestorLarroca** [comment]
Esto es  lo que tengo al iniciar el el programa:
[sudo] password for nestor: 

20/05/2018 04:42:05.598 - [de.fhg.iais.roberta.usb.Main.configureLogger] - [INFO] - Logging to file: /root/OpenRobertaUSB/OpenRobertaUSB.log
20/05/2018 04:42:06.015 - [de.fhg.iais.roberta.usb.Main$1.getLocals] - [CONFIG] - Language en
20/05/2018 04:42:06.019 - [de.fhg.iais.roberta.connection.EV3USBConnector.<init>] - [CONFIG] - Robot ip 10.0.1.1
Found NXT: Unknown 001653105D1C
20/05/2018 04:42:27.759 - [de.fhg.iais.roberta.usb.Main.main] - [INFO] - NXT found!
20/05/2018 04:42:27.759 - [de.fhg.iais.roberta.ui.UIController.setConnector] - [CONFIG] - GUI setup done. Using NXTUSBBTConnector
20/05/2018 04:42:27.760 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Starting NXT Connector Thread.
20/05/2018 04:42:27.773 - [de.fhg.iais.roberta.connection.NXTUSBBTConnector.run] - [CONFIG] - Server address lab.open-roberta.org:80
Found NXT: Unknown 001653105D1C

**Comment by boonto** [comment]
This problem should be solved with the release of the specialized [USBNXTProgram](https://github.com/OpenRoberta/robertalab-usbprogram-nxt). Please open another issue if the problem persists.
