### ISSUE TITLE
Windows system shows wrong version after installation

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab-usbprogram#12]
![image](https://user-images.githubusercontent.com/1613069/30854491-19507ab0-a2b2-11e7-9653-8edfd413351b.png)

**Comment by boonto** [comment]
This problem was fixed some time ago. 

![capture](https://user-images.githubusercontent.com/7438960/51739570-1c159000-2092-11e9-9cb7-e96598414c52.PNG)
