### ISSUE TITLE
Connection on a Microsoft Surface with Windows 10 not working

### ISSUE THREAD

**Issue by MagicMarvMan** [OpenRoberta/robertalab-usbprogram#14]
Hello.

The usb assistant does not recognize my Lego Mindstorms EV3 robot on a Windows 10 environment on an Microsoft Surface, it doesn't even display an error, but on my mac it works without changing any settings.

I hope I could help you,
MagicMarvMan

**Comment by boonto** [comment]
Can you post the content of your OpenRobertaUSB.log?
It can be found here:
`C:\Users\username\AppData\Roaming\OpenRobertaUSB\` (replace username with your actual username).

Did you try different USB ports?

**Comment by boonto** [comment]
We don't really have enough information to tackle this issue, so I will close this for now. If this issue still persists, you can reopen it and we can look into the problem.
