### ISSUE TITLE
Could not establish usb connection to nxt brick

### ISSUE THREAD

**Issue by kerimashram** [OpenRoberta/robertalab-usbprogram#25]
after installing usb program, starting prog and connecting nxt brick to computer, there was no connection establish. Even waiting aprox. 30 mins.
shell script remained by 0% 

computer os 10.15.4 OS Catalina

**Comment by boonto** [comment]
This program is outdated. Please check out the special [robertalab-usbprogram-nxt](https://github.com/OpenRoberta/robertalab-usbprogram-nxt). If you have any additional problems please create an issue there. NXT is very finicky.
