### ISSUE TITLE
Creating .deb file Ubuntu

### ISSUE THREAD

**Issue by gregorsamsa183** [OpenRoberta/robertalab-usbprogram#8]
Proper packaging Debian scheme should be implemented for Linux OS. I've looked through some solutions but they seem to be not working.

**Comment by boonto** [comment]
I added the idea to the [wiki entry](https://github.com/OpenRoberta/robertalab/wiki/Open-Roberta-Robot-Connection-Program). An updated ticket will be created if we decide to tackle this.
